#+TITLE: Literate Org README
#+AUTHOR: Gorka Eraña
#+EMAIL: eranagorka@gmail.com
#+DATE: <2026-01-16 Fri>
#+CREATED: 2021-05-12
#+STARTUP: hidestars indent overview
# #+PROPERTY: header-args :results silent :tangle "./init.el"
# #+OPTIONS: toc:2

I finally got around to using [[https://github.com/syl20bnr/spacemacs][spacemacs]] and now I can replace the previous bespoke =init.el= with a simple algorithm.

* Steps
** Clone spacemacs
#+begin_src bash
  git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
#+end_src
** Choose mode and distribution
Upon first spacemacs start up choose "emacs mode" and the "standard distribution".
** Within =~/.spacemacs=
*** Under =dotspacemacs-configuration-layers=
- Uncomment: =lsp=, =markdown=, =org=, =treemacs=.
- Add: =docker=, =dockerfile=.
- Activate =vterm= with the below configuration. (Note: it will have to be compiled the first time it is used.)
#+begin_src emacs-lisp
  (shell :variables
         shell-default-height 30
         shell-default-position 'bottom
         shell-default-shell 'vterm)
#+end_src
- Enable =magit= and =magit-delta= by replacing =git= with
#+begin_src emacs-lisp
  (git :variables git-enable-magit-delta-plugin t)
#+end_src
- Switch on a couple of org mode goodies by replacing =org= with, where =[...]= is a placeholder for the =org-journal= directory path
#+begin_src emacs-lisp
  (org :variables
       org-enable-modern-support t
       org-enable-appear-support t
       org-enable-org-journal-support t
       org-journal-dir "[...]"
       org-journal-file-format "%Y-%m-%d.org"
       org-journal-date-prefix "#+TITLE: "
       org-journal-date-format "%A, %B %d %Y"
       org-journal-time-prefix "* "
       org-journal-time-format "")
#+end_src
This configures org-journal with ISO 8601 daily files (=YYYY-MM-DD.org=), where each file has a =#+TITLE:= header with the full date, and new time entries use a top-level =*= heading.
*** Under =dotspacemacs/init=
Set relative line numbers with ~dotspacemacs-line-numbers 'relative~
*** Under =dotspacemacs/user-init=
Add
#+begin_src emacs-lisp
  (setq
   ;; More todo keywords
   org-todo-keywords '((sequence "TODO" "IN-PROGRESS" "WAITING" "CANCELLED" "DONE"))
   ;; And colours for them
   org-todo-keyword-faces '(
                            ("TODO" . (:foreground "orange" :weight bold))
                            ("IN-PROGRESS" . (:foreground "yellow" :weight bold))
                            ("WAITING" . (:foreground "red" :weight bold))
                            ("CANCELLED" . (:foreground "black" :weight bold))
                            )
   org-startup-indented t
   org-hide-leading-stars t
   )
  ;; Toggle treemacs more easily
  (global-set-key [f8] 'treemacs)
  ;; Open files with a single click in treemacs
  (define-key treemacs-mode-map [mouse-1] #'treemacs-single-click-expand-action)
#+end_src
*** Under =dotspacemacs/user-config=
Add the below, where =[...]= is a placeholder for the files and folders you want to be included in Org Agenda. The =auto-mode-alist= entry ensures journal files automatically open in =org-journal-mode=.
#+begin_src emacs-lisp
  (with-eval-after-load 'org
    (add-to-list 'org-agenda-files "[...]"))
  (with-eval-after-load 'org-journal
    (add-to-list 'auto-mode-alist '("/journal/[0-9]\\{4\\}-[0-9]\\{2\\}-[0-9]\\{2\\}\\.org\\'" . org-journal-mode)))
#+end_src
*** Under =dotspacemacs-additional-packages=
Set it to ='(ripgrep)=
* Potential improvements
Ideally the steps described in the previous section would happen automatically. E.g. via =org-babel-tangle= into a bash script or something.
